# Generated by Django 4.2.4 on 2024-03-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_d', models.CharField(max_length=30)),
                ('nombres_d', models.CharField(max_length=50)),
                ('apellidos_d', models.CharField(max_length=50)),
                ('correo_p', models.EmailField(max_length=254)),
                ('direccion_d', models.CharField(max_length=50)),
                ('telefono_d', models.CharField(max_length=10)),
                ('foto_d', models.ImageField(upload_to='')),
                ('activo_d', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_s', models.CharField(max_length=30)),
                ('horario_s', models.CharField(max_length=30)),
                ('ubicacion_s', models.CharField(max_length=50)),
                ('activo_s', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30)),
                ('nombres_p', models.CharField(max_length=50)),
                ('apellidos_p', models.CharField(max_length=50)),
                ('correo_p', models.EmailField(max_length=254)),
                ('edad_p', models.IntegerField()),
                ('direccion_p', models.CharField(max_length=50)),
                ('telefono_p', models.CharField(max_length=10)),
                ('foto_p', models.ImageField(upload_to='')),
                ('activo_p', models.CharField(max_length=6)),
                ('doctor_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.doctores')),
                ('sede_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.sedes')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.AddField(
            model_name='doctores',
            name='sede_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.sedes'),
        ),
    ]
