# Generated by Django 4.2.4 on 2024-03-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='activo_s',
            field=models.CharField(max_length=8),
        ),
    ]
