# Generated by Django 4.2.4 on 2024-03-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0002_alter_sedes_activo_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctores',
            old_name='correo_p',
            new_name='correo_d',
        ),
    ]
