# Generated by Django 4.2.4 on 2024-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0003_rename_correo_p_doctores_correo_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctores',
            name='foto_d',
            field=models.ImageField(null=True, upload_to='doctores/'),
        ),
    ]
