# Generated by Django 4.2.4 on 2024-03-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0006_alter_pacientes_activo_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='identificacion',
            new_name='identificacion_p',
        ),
    ]
