# Generated by Django 4.2.4 on 2024-03-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0007_rename_identificacion_pacientes_identificacion_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='foto_p',
            field=models.ImageField(upload_to='pacientes/'),
        ),
    ]
